web:  
  build: .
  ports:
    - "8080:80"
  volumes:
    - .:/srv/www
  links:
    - db
    - cache
db:  
  image: mysql:5.6
  environment:
    MYSQL_ROOT_PASSWORD: password
    MYSQL_DATABASE: thermostat
    MYSQL_USER: thermostat
    MYSQL_PASSWORD: password
cache:  
  image: memcached:latest
